#!/usr/bin/env bash

log=$(platex -interaction=nonstopmode main_discussion.tex)
status=$?

if [ $status -ne 0 ]; then
    echo "エラーが起こりました"
    parseTexError.js "$log"
    exit 0;
fi

platex main_discussion.tex > /dev/null 2>&1
dvipdfmx main_discussion.dvi


