#!/usr/bin/env bash


log=$(platex -interaction=nonstopmode main_intro.tex)
status=$?

if [ $status -ne 0 ]; then
    echo "エラーが起こりました"
    parseTexError.js "$log"
    exit 0;
fi

platex main_intro.tex > /dev/null 2>&1
dvipdfmx main_intro.dvi


